
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vtrxhfwaxrknnjbpcwqd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ0cnhoZndheHJrbm5qYnBjd3FkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMxNzM5MzEsImV4cCI6MjA1ODc0OTkzMX0.o4yzskWYVQhrgv3zwdtTJVz0k8qFfOW0pFN965vKe9k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
